language: node_js
node_js:
  - "12.3.1"

branches:
  only:
    - master

before_script:
  - npx ng analytics on
  - yarn install --frozen-lockfile

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: dist
